version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: todo-postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
      POSTGRES_DB: tododb
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: todo-backend-dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: todouser
      DB_PASSWORD: todopass
      DB_NAME: tododb
      JWT_SECRET: dev-secret-key-change-in-production
      FRONTEND_URL: http://localhost:8080
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - backend-network
      - frontend-network
    command: npm run dev
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: todo-frontend-dev
    ports:
      - "8080:8080"
    environment:
      VITE_API_URL: http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - frontend-network
    command: npm run dev
    stdin_open: true
    tty: true

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  postgres-dev-data:
    driver: local
